### ISSUE TITLE
UTF-8 encoding issues for encoder-decoder and transformer baselines

### ISSUE THREAD

**Issue by saujasv** [sigmorphon/2020#5]
I was able to successfully run the `fst` baselines, but when I try to run the `preprocess` script for the `encoder-decoder` or `transformer` baselines, I get the following error:
```
Namespace(alignfile=None, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='data-bin/arm', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, seed=1, source_lang='arm.graphemes', srcdict=None, target_lang='arm.phonemes', task='translation', tbmf_wrapper=False, tensorboard_logdir='', testpref=None, tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer='space', trainpref='train', user_dir=None, validpref='dev', workers=1)
Traceback (most recent call last):
  File "<...>/miniconda3/envs/task1/bin/fairseq-preprocess", line 8, in <module>
    sys.exit(cli_main())
  File "<...>/miniconda3/envs/task1/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 265, in cli_main
    main(args)
  File "<...>/miniconda3/envs/task1/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 81, in main
    src_dict = build_dictionary([train_path(args.source_lang)], src=True)
  File "<...>/miniconda3/envs/task1/lib/python3.7/site-packages/fairseq_cli/preprocess.py", line 54, in build_dictionary
    padding_factor=args.padding_factor,
  File "<...>/miniconda3/envs/task1/lib/python3.7/site-packages/fairseq/tasks/fairseq_task.py", line 52, in build_dictionary
    Dictionary.add_file_to_dictionary(filename, d, tokenizer.tokenize_line, workers)
  File "<...>/miniconda3/envs/task1/lib/python3.7/site-packages/fairseq/data/dictionary.py", line 304, in add_file_to_dictionary
    merge_result(Dictionary._add_file_to_dictionary_single_worker(filename, tokenize, dict.eos_word))
  File "<...>/miniconda3/envs/task1/lib/python3.7/site-packages/fairseq/data/dictionary.py", line 275, in _add_file_to_dictionary_single_worker
    line = f.readline()
  File "<...>/miniconda3/envs/task1/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
```
The issue persists when I try to skip Armernian and preprocess Bulgarian text as well. The first part of the script runs successfully to generate `.graphemes` and `.phonemes` files, but the second part of the script throws this error. How do I resolve this?

**Comment by kylebgorman** [comment]
I can't replicate this, and the preprocessing script is pretty vanilla, so
I'm guessing it's platform-specific.

Since the error is an encoding one, and since all assets are just UTF-8, I
would suggest that you check your language/locale settings to make sure
they can handle UTF-8 inputs and outputs?

**Comment by kylebgorman** [comment]
Any update @saujasv or should I close this issue?

**Comment by saujasv** [comment]
Oh, I'm sorry, I forgot to close this issue. I had some locale issues that I was able to resolve.

Thanks!
